# Generated by Django 2.1.4 on 2018-12-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='decimal',
            field=models.FloatField(null=True),
        ),
    ]
