# Generated by Django 2.1.4 on 2018-12-24 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rateme', '0005_auto_20181212_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProcessing',
            fields=[
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='processing', serialize=False, to='rateme.SubmissionImage')),
                ('texture', models.ImageField(upload_to='')),
                ('shape_coefficients', models.CharField(max_length=4096)),
                ('color_coefficients', models.CharField(max_length=4096)),
                ('expression_coefficients', models.CharField(max_length=4096)),
            ],
        ),
    ]
