# Generated by Django 2.1.4 on 2018-12-29 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rateme', '0008_submissionimage_face_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceProcessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texture', models.ImageField(upload_to='')),
                ('shape_coefficients', models.CharField(max_length=4096)),
                ('color_coefficients', models.CharField(max_length=4096)),
                ('expression_coefficients', models.CharField(max_length=4096)),
                ('pitch', models.FloatField()),
                ('yaw', models.FloatField()),
                ('roll', models.FloatField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_processings', to='rateme.SubmissionImage')),
            ],
        ),
    ]
