# Generated by Django 2.1.4 on 2018-12-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateme', '0009_faceprocessing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
