# Generated by Django 2.1.4 on 2019-01-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateme', '0010_auto_20181229_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='calculated_rating',
            field=models.FloatField(null=True),
        ),
    ]
