# Generated by Django 2.1.4 on 2019-01-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateme', '0012_auto_20190107_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceprocessing',
            name='texture_coefficients',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
