# Generated by Django 2.1.4 on 2019-02-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateme', '0013_faceprocessing_texture_coefficients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='faceprocessing',
            name='texture',
            field=models.ImageField(max_length=4096, upload_to=''),
        ),
        migrations.AlterField(
            model_name='imageprocessing',
            name='texture',
            field=models.ImageField(max_length=4096, upload_to=''),
        ),
        migrations.AlterField(
            model_name='submissionimage',
            name='image',
            field=models.ImageField(max_length=4096, upload_to=''),
        ),
    ]
