# Generated by Django 2.1.7 on 2019-03-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateme', '0014_auto_20190211_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceprocessing',
            name='landmarks',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='faceprocessing',
            name='rect_h',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='faceprocessing',
            name='rect_w',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='faceprocessing',
            name='rect_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='faceprocessing',
            name='rect_y',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='faceprocessing',
            name='roi',
            field=models.ImageField(max_length=4096, null=True, upload_to=''),
        ),
    ]
